# Generated by Django 6.1.1 on 2026-09-17 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0006_alter_dailychallenge_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('challenge_type', models.CharField(default='solo', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('invited', 'Invited'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='draft', max_length=16)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('friends', 'Friends'), ('public', 'Public')], default='friends', max_length=16)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='games.game')),
                ('game_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='games.gamesession')),
            ],
            options={
                'db_table': 'challenges_challenge',
            },
        ),
        migrations.CreateModel(
            name='ChallengeInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='pending', max_length=16)),
                ('message', models.CharField(blank=True, default='', max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='challenges.challenge')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_challenge_invites', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_challenge_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenges_challenge_invitation',
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('left', 'Left'), ('completed', 'Completed')], db_index=True, default='invited', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.BigIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenges_challenge_participant',
            },
        ),
        migrations.CreateModel(
            name='ChallengeResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.BigIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='challenges.challenge')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='challenges.challengeparticipant')),
            ],
            options={
                'db_table': 'challenges_challenge_result',
            },
        ),
        migrations.CreateModel(
            name='ChallengeRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready'), ('live', 'Live'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=16)),
                ('maximum_participants', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='challenges.challenge')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_challenge_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenges_challenge_room',
            },
        ),
        migrations.CreateModel(
            name='ChallengeRoomMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('left', 'Left')], db_index=True, default='active', max_length=16)),
                ('is_host', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='challenges.challengeroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenges_challenge_room_member',
            },
        ),
        migrations.CreateModel(
            name='ChallengeTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='challenges.challenge')),
            ],
            options={
                'db_table': 'challenges_challenge_team',
            },
        ),
        migrations.CreateModel(
            name='ChallengeTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='challenges.challengeteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenges_challenge_team_member',
            },
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['status', '-created_at'], name='challenge_status_created'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['creator', '-created_at'], name='challenge_creator_created'),
        ),
        migrations.AddConstraint(
            model_name='challengeinvitation',
            constraint=models.UniqueConstraint(fields=('challenge', 'recipient'), name='uniq_challenge_invite_recipient'),
        ),
        migrations.AddIndex(
            model_name='challengeparticipant',
            index=models.Index(fields=['challenge', 'status'], name='challenge_part_status'),
        ),
        migrations.AddConstraint(
            model_name='challengeparticipant',
            constraint=models.UniqueConstraint(fields=('challenge', 'user'), name='uniq_challenge_participant_pair'),
        ),
        migrations.AddIndex(
            model_name='challengeresult',
            index=models.Index(fields=['challenge', '-score'], name='challenge_result_score'),
        ),
        migrations.AddIndex(
            model_name='challengeroom',
            index=models.Index(fields=['status', 'room_code'], name='challenge_room_code'),
        ),
        migrations.AddIndex(
            model_name='challengeroom',
            index=models.Index(fields=['host', '-created_at'], name='challenge_room_host'),
        ),
        migrations.AddIndex(
            model_name='challengeroommember',
            index=models.Index(fields=['room', 'status'], name='challenge_room_member_status'),
        ),
        migrations.AddConstraint(
            model_name='challengeroommember',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='uniq_room_member_pair'),
        ),
        migrations.AddConstraint(
            model_name='challengeteam',
            constraint=models.UniqueConstraint(fields=('challenge', 'name'), name='uniq_team_per_challenge'),
        ),
        migrations.AddConstraint(
            model_name='challengeteammember',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='uniq_team_member_pair'),
        ),
    ]
