# Generated by Django 6.1.1 on 2026-09-12 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=160)),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('accent', models.CharField(blank=True, default='', max_length=16)),
                ('category', models.CharField(default='learning', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'interest',
                'verbose_name_plural': 'interests',
                'db_table': 'profiles_interest',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PlayStyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=180)),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('accent', models.CharField(blank=True, default='', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'play style',
                'verbose_name_plural': 'play styles',
                'db_table': 'profiles_play_style',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('bio', models.CharField(blank=True, default='', max_length=240)),
                ('language', models.CharField(default='en', max_length=8)),
                ('country', models.CharField(blank=True, default='', max_length=8)),
                ('skill_level', models.CharField(blank=True, default='beginner', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'profiles_profile',
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='profiles.interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user interest',
                'verbose_name_plural': 'user interests',
                'db_table': 'profiles_user_interest',
                'constraints': [models.UniqueConstraint(fields=('user', 'interest'), name='uniq_user_interest')],
            },
        ),
        migrations.CreateModel(
            name='UserPlayStyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('play_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='profiles.playstyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_play_styles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user play style',
                'verbose_name_plural': 'user play styles',
                'db_table': 'profiles_user_play_style',
                'constraints': [models.UniqueConstraint(fields=('user', 'play_style'), name='uniq_user_play_style')],
            },
        ),
    ]
