# Generated by Django 6.1.1 on 2026-09-12 17:01

import apps.accounts.managers
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityDocumentUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('document', models.FileField(blank=True, max_length=255, upload_to='verification/pending/')),
                ('document_type', models.CharField(blank=True, default='', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('consumed', 'Consumed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('region', models.CharField(blank=True, default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'identity document upload',
                'verbose_name_plural': 'identity document uploads',
                'db_table': 'accounts_identity_document_upload',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector_id', models.CharField(blank=True, db_index=True, help_text='Permanent, unique, immutable Vector Strike ID (server generated).', max_length=16, unique=True)),
                ('username', models.CharField(db_index=True, help_text='Unique platform handle.', max_length=30, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age_group', models.CharField(blank=True, help_text='Preliminary onboarding bucket.', max_length=16)),
                ('age_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=24)),
                ('account_status', models.CharField(choices=[('pending', 'Pending onboarding'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='pending', max_length=16)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('region', models.CharField(blank=True, default='', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GuardianRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_name', models.CharField(blank=True, default='', max_length=120)),
                ('guardian_phone', models.CharField(blank=True, default='', max_length=32)),
                ('relationship_type', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('consent_status', models.CharField(choices=[('pending', 'Pending consent'), ('consented', 'Consented'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('consent_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('in_person', 'In person'), ('none', 'None')], default='none', max_length=16)),
                ('consent_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('consent_requested_at', models.DateTimeField(auto_now_add=True)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relationship', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'guardian relationship',
                'verbose_name_plural': 'guardian relationships',
                'db_table': 'accounts_guardian_relationship',
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.CharField(blank=True, default='', max_length=40)),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'onboarding progress',
                'verbose_name_plural': 'onboarding progress',
                'db_table': 'accounts_onboarding_progress',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=24)),
                ('provider', models.CharField(choices=[('document', 'Document upload'), ('external_provider', 'External verification provider'), ('none', 'None')], default='none', max_length=24)),
                ('region', models.CharField(blank=True, default='', max_length=8)),
                ('document_type', models.CharField(blank=True, default='', max_length=8)),
                ('document', models.FileField(blank=True, upload_to='verification/verified/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_by', to='accounts.identitydocumentupload')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verification',
                'verbose_name_plural': 'verifications',
                'db_table': 'accounts_verification',
            },
        ),
    ]
