# Generated by Django 6.1.1 on 2026-09-13 04:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_vector_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='Provider-level reference for this verification (e.g. external supplier ref).', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('pending_onboarding', 'Pending onboarding'), ('pending_verification', 'Pending verification'), ('active', 'Active'), ('restricted', 'Restricted'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated'), ('closed', 'Closed')], default='pending_onboarding', max_length=24),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='not_required', max_length=24),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=24),
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('otp_hash', models.CharField(db_index=True, max_length=64)),
                ('verified', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'phone verification',
                'verbose_name_plural': 'phone verifications',
                'db_table': 'accounts_phone_verification',
            },
        ),
        migrations.CreateModel(
            name='OneTimeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('email_verification', 'Email verification'), ('password_reset', 'Password reset')], max_length=32)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'one-time token',
                'verbose_name_plural': 'one-time tokens',
                'db_table': 'accounts_one_time_token',
                'indexes': [models.Index(fields=['user', 'purpose'], name='ot_token_user_purpose')],
            },
        ),
    ]
