# Generated by Django 6.1.1 on 2026-09-17 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0006_alter_dailychallenge_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('tagline', models.CharField(blank=True, default='', max_length=140)),
                ('banner', models.CharField(blank=True, default='', max_length=255)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('game_type', models.CharField(choices=[('solo', 'Solo'), ('team', 'Team'), ('both', 'Both')], default='solo', max_length=16)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('invite', 'Invite only')], default='public', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('live', 'Live'), ('ending_soon', 'Ending soon'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='upcoming', max_length=24)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('registration_start_at', models.DateTimeField(blank=True, null=True)),
                ('registration_end_at', models.DateTimeField(blank=True, null=True)),
                ('minimum_age', models.PositiveIntegerField(default=0)),
                ('maximum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('entry_type', models.CharField(blank=True, default='', max_length=24)),
                ('entry_requirement', models.CharField(blank=True, default='', max_length=255)),
                ('reward_configuration', models.JSONField(blank=True, default=dict)),
                ('maximum_participants', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='games.game')),
            ],
            options={
                'db_table': 'tournaments_tournament',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('disqualified', 'Disqualified'), ('finished', 'Finished')], db_index=True, default='active', max_length=24)),
                ('raw_score', models.BigIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('result_metadata', models.JSONField(blank=True, default=dict)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tournaments_participant',
            },
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=80)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournaments_round',
            },
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.BigIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tournaments.tournamentparticipant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tournaments.tournament')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tournaments.tournamentround')),
            ],
            options={
                'db_table': 'tournaments_result',
            },
        ),
        migrations.CreateModel(
            name='TournamentRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True, default='')),
                ('kind', models.CharField(blank=True, default='', max_length=32)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournaments_rule',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status', 'start_at'], name='trn_status_start'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['is_featured', 'status'], name='trn_featured_status'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['game', 'status'], name='trn_game_status'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['tournament', 'status'], name='part_tournament_status'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['user', '-joined_at'], name='part_user_joined'),
        ),
        migrations.AddConstraint(
            model_name='tournamentparticipant',
            constraint=models.UniqueConstraint(fields=('tournament', 'user'), name='uniq_tournament_user_participant'),
        ),
        migrations.AddIndex(
            model_name='tournamentround',
            index=models.Index(fields=['tournament', 'number'], name='round_tournament_number'),
        ),
        migrations.AddConstraint(
            model_name='tournamentround',
            constraint=models.UniqueConstraint(fields=('tournament', 'number'), name='uniq_tournament_round_number'),
        ),
        migrations.AddIndex(
            model_name='tournamentresult',
            index=models.Index(fields=['tournament', '-score'], name='res_tournament_score'),
        ),
        migrations.AddIndex(
            model_name='tournamentresult',
            index=models.Index(fields=['participant', 'round'], name='res_participant_round'),
        ),
        migrations.AddIndex(
            model_name='tournamentrule',
            index=models.Index(fields=['tournament', 'sort_order'], name='rule_tournament_sort'),
        ),
    ]
