# Generated by Django 6.1.1 on 2026-09-13 04:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('kind', models.CharField(default='lifetime', max_length=30)),
                ('target', models.PositiveIntegerField(default=1)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'achievement',
                'verbose_name_plural': 'achievements',
                'db_table': 'games_achievement',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=220)),
                ('banner', models.CharField(blank=True, default='', max_length=255)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('ended', 'Ended')], default='upcoming', max_length=16)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'db_table': 'games_event',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('tagline', models.CharField(blank=True, default='', max_length=140)),
                ('difficulty', models.IntegerField(choices=[(1, 'Relaxed'), (2, 'Easy'), (3, 'Moderate'), (4, 'Challenging'), (5, 'Expert')], default=2)),
                ('game_type', models.CharField(choices=[('solo', 'Solo'), ('versus', 'Versus'), ('co-op', 'Co-operative'), ('multiplayer', 'Multiplayer')], default='solo', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('minimum_age', models.PositiveIntegerField(default=6, null=True)),
                ('maximum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('content_rating', models.CharField(blank=True, default='', max_length=16)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=255)),
                ('banner', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
                'db_table': 'games_game',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'game category',
                'verbose_name_plural': 'game categories',
                'db_table': 'games_category',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=220)),
                ('kind', models.CharField(default='first_game', max_length=40)),
                ('target', models.PositiveIntegerField(default=1)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'mission',
                'verbose_name_plural': 'missions',
                'db_table': 'games_mission',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, default='', max_length=220)),
                ('reward_xp', models.PositiveIntegerField(default=50)),
                ('goal', models.CharField(blank=True, default='', max_length=160)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='games.game')),
            ],
            options={
                'verbose_name': 'daily challenge',
                'verbose_name_plural': 'daily challenges',
                'db_table': 'games_daily_challenge',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='games.gamecategory'),
        ),
        migrations.AddField(
            model_name='game',
            name='secondary_categories',
            field=models.ManyToManyField(blank=True, related_name='secondary_games', to='games.gamecategory'),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned', to='games.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user achievement',
                'verbose_name_plural': 'user achievements',
                'db_table': 'games_user_achievement',
            },
        ),
        migrations.CreateModel(
            name='UserGameProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.PositiveIntegerField(default=0)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_progress', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user game progress',
                'verbose_name_plural': 'user game progress',
                'db_table': 'games_user_game_progress',
            },
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='games.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user mission',
                'verbose_name_plural': 'user missions',
                'db_table': 'games_user_mission',
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', 'release_date'], name='games_game_status_cd0572_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['category', 'status'], name='games_game_categor_4ebbb6_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', '-release_date'], name='games_game_status_3bc6f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='uniq_user_achievement'),
        ),
        migrations.AddIndex(
            model_name='usergameprogress',
            index=models.Index(fields=['user', '-last_played_at'], name='games_user__user_id_c2ec48_idx'),
        ),
        migrations.AddConstraint(
            model_name='usergameprogress',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='uniq_user_game'),
        ),
        migrations.AddConstraint(
            model_name='usermission',
            constraint=models.UniqueConstraint(fields=('user', 'mission'), name='uniq_user_mission'),
        ),
    ]
