# Generated by Django 6.1.1 on 2026-09-14 04:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_seed_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], db_index=True, default='started', max_length=16)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('accuracy', models.PositiveIntegerField(default=0)),
                ('level_reached', models.PositiveIntegerField(default=1)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'game session',
                'verbose_name_plural': 'game sessions',
                'db_table': 'games_game_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='gamecategory',
            options={'ordering': ['sort_order', 'codename', 'label'], 'verbose_name': 'game category', 'verbose_name_plural': 'game categories'},
        ),
        migrations.AddField(
            model_name='game',
            name='controls',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='mechanics',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='game',
            name='play_kind',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='accent',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='codename',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='usergameprogress',
            name='playtime_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', 'difficulty'], name='games_game_status_1bd675_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', 'game_type', 'release_date'], name='games_game_status_bda225_idx'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.game'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user', '-started_at'], name='games_game__user_id_519ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user', 'game', 'status'], name='games_game__user_id_9236a5_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['game', 'status', 'completed_at'], name='games_game__game_id_0ea1b5_idx'),
        ),
    ]
