# Generated by Django 6.1.1 on 2026-09-17 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_title_rebrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychallenge',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_challenge', to='games.game'),
        ),
    ]
