# Generated by Django 6.1.1 on 2026-09-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_dailychallenge_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_modes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='orientation',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='game',
            name='visual_style',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='best_combo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='completion_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='difficulty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_mode',
            field=models.CharField(db_index=True, default='quick', max_length=20),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='mistakes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usergameprogress',
            name='best_accuracy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usergameprogress',
            name='best_combo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usergameprogress',
            name='best_time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
